# /// script
# requires-python = ">=3.11,<3.14"
# dependencies = ["pymhf[gui]==0.2.4"]
#
# [tool.pymhf]
# exe = "NMS.exe"
# steam_gameid = 275850
# start_paused = false
# interactive_console = false
#
# [tool.pymhf.logging]
# shown = false
# log_dir = "{CURR_DIR}"
# log_level = "info"
#
# [tool.pymhf.gui]
# shown = true
# always_on_top = false
# ///
# AutoPet 0.4.1 EXPERIMENTAL — optional native-biome preference pending live validation.
# Generated by build.py. Edit src/, then rebuild.

"""Pure decision policy for summoning an owned pet after leaving a ship.

This module neither reads game state nor calls the game. The adapter supplies
observations and performs the one returned summon request.
"""

import math


class AutoPetPolicy:
    """Remember a manual favorite and allow one in-flight request per exit.

    Acceptance finishes the exit; rejection retains its fixed choice for a
    paced retry. The adapter supplies fresh native checks and retry pacing.

    ``now`` must come from one monotonic clock. A backward clock step cancels
    the current exit; invalid timestamps cancel it and raise ``ValueError``.
    On-foot stability starts with the first positive observation, so time in
    a forbidden location, in transit, or before that observation cannot count
    toward it. The adapter supplies the game's supported summon locations.
    """

    def __init__(self, delay_seconds=1.5, expiry_seconds=None):
        self._delay = self._finite_number(delay_seconds, "delay_seconds")
        self._expiry = (None if expiry_seconds is None
                        else self._finite_number(expiry_seconds, "expiry_seconds"))
        if self._delay < 0:
            raise ValueError("delay_seconds must be non-negative")
        if self._expiry is not None and self._expiry <= 0:
            raise ValueError("expiry_seconds must be positive")
        self.reset()

    @staticmethod
    def _finite_number(value, name):
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f"{name} must be a finite number")
        try:
            result = float(value)
        except (ValueError, OverflowError):
            raise ValueError(f"{name} must be a finite number") from None
        if not math.isfinite(result):
            raise ValueError(f"{name} must be a finite number")
        return result

    def _cancel_pending(self):
        self._ejected_at = None
        self._stable_since = None
        self._exit_slot = None
        self._in_flight = False

    def _observe_time(self, now):
        try:
            timestamp = self._finite_number(now, "now")
        except ValueError:
            self._cancel_pending()
            raise
        reversed_time = self._last_time is not None and timestamp < self._last_time
        self._last_time = timestamp
        if reversed_time:
            self._cancel_pending()
            return None
        return timestamp

    def remember(self, slot: int):
        """Record a manual or restored choice; replacing it cancels an old exit."""
        if isinstance(slot, bool) or not isinstance(slot, int) or not 0 <= slot < 30:
            raise ValueError("slot must be an integer from 0 through 29")
        self._slot = slot
        self._cancel_pending()

    def eject(self, now: float, *, random_selection=False):
        """Arm a manual choice, or defer this exit's choice to the adapter.

        Random mode may arm without a manual favorite. Its later choice never
        changes that favorite or restarts the exit deadline/stability clock.
        """
        if type(random_selection) is not bool:
            raise ValueError("random_selection must be a bool")
        timestamp = self._observe_time(now)
        if timestamp is None:
            return
        self._cancel_pending()
        if self._slot is not None or random_selection:
            self._ejected_at = timestamp
            self._exit_slot = None if random_selection else self._slot

    def select_for_exit(self, slot: int):
        """Bind an unselected pending exit once, without changing its clocks."""
        if isinstance(slot, bool) or not isinstance(slot, int) or not 0 <= slot < 30:
            raise ValueError("slot must be an integer from 0 through 29")
        if not self.pending:
            return False
        if self._exit_slot is not None:
            raise ValueError("this exit already has a companion")
        self._exit_slot = slot
        return True

    def enter_ship(self):
        """Cancel an exit without forgetting the last manual pet choice."""
        self._cancel_pending()

    def reset(self):
        """Forget all session state, for example when loading another save."""
        self._slot = None
        self._last_time = None
        self._cancel_pending()

    @property
    def last_slot(self) -> int | None:
        """Last remembered manual choice in this session, if any."""
        return self._slot

    @property
    def pending(self) -> bool:
        """Whether an exit is still waiting for a possible summon request."""
        return self._ejected_at is not None

    @property
    def pending_slot(self) -> int | None:
        """Companion bound to this exit, separate from the manual favorite."""
        return self._exit_slot

    def resolve(self, accepted: bool):
        """Complete one queue attempt; rejection retains the same exit/choice."""
        if type(accepted) is not bool:
            raise ValueError("accepted must be a bool")
        if not self._in_flight:
            return False
        if accepted:
            self._cancel_pending()
        else:
            self._in_flight = False
        return True

    def tick(
        self,
        now: float,
        *,
        on_foot_in_summon_location: bool,
        active_pet: int,
        native_pending_pet: int,
        eligible: bool,
    ) -> int | None:
        """Offer one slot, or None; the adapter must resolve its queue result.

        An existing or natively queued pet cancels the pending exit. Unknown
        index sentinels cannot summon either: both indices must equal -1.
        The default has no expiry. An optional finite deadline is available to
        callers that explicitly need one. Retry pacing belongs to the adapter.
        """
        timestamp = self._observe_time(now)
        if timestamp is None or self._ejected_at is None:
            return None
        if self._expiry is not None and timestamp - self._ejected_at >= self._expiry:
            self._cancel_pending()
            return None
        if active_pet >= 0 or native_pending_pet >= 0:
            self._cancel_pending()
            return None
        if not on_foot_in_summon_location:
            self._stable_since = None
            return None
        if self._stable_since is None:
            self._stable_since = timestamp
        if timestamp - self._stable_since < self._delay:
            return None
        if (not eligible or active_pet != -1 or native_pending_pet != -1
                or self._exit_slot is None or self._in_flight):
            return None
        slot = self._exit_slot
        self._in_flight = True
        return slot


"""Bounded, atomic local storage for a pet choice per save identity.

The caller supplies a mod-owned path. This module does not locate, open, or
modify game saves and performs no filesystem operations during import.
"""

import json
import os
from pathlib import Path
import tempfile


class SelectionStoreError(Exception):
    """A selection file could not be read, validated, or replaced safely."""


class PetSelectionStore:
    """Persist a 16-byte pet identity and a last-known slot, separately per save.

    Invalid caller arguments raise ``ValueError``. Invalid or inaccessible
    existing files raise ``SelectionStoreError`` and are never overwritten.
    Every operation re-reads the file; instances retain no cached selections.
    The runtime should use one writer, not concurrent mod processes.
    """

    SCHEMA = 1
    MAX_BYTES = 1024 * 1024
    MAX_ENTRIES = 256
    MAX_KEY_LENGTH = 256

    def __init__(self, path: Path):
        self.path = Path(path)

    @classmethod
    def _validate_key(cls, save_key):
        if not isinstance(save_key, str) or not 1 <= len(save_key) <= cls.MAX_KEY_LENGTH:
            raise ValueError("save_key must be a nonempty string of at most 256 characters")

    @staticmethod
    def _validate_slot(slot):
        if type(slot) is not int or not 0 <= slot <= 29:
            raise ValueError("slot must be an integer from 0 to 29")

    @staticmethod
    def _unique_object(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise SelectionStoreError("Selection file contains duplicate JSON keys")
            result[key] = value
        return result

    @classmethod
    def _validate_document(cls, document):
        if not isinstance(document, dict) or set(document) != {"schema", "selections"}:
            raise SelectionStoreError("Selection file has an invalid document structure")
        if type(document["schema"]) is not int or document["schema"] != cls.SCHEMA:
            raise SelectionStoreError("Selection file uses an unsupported schema")
        selections = document["selections"]
        if not isinstance(selections, dict) or len(selections) > cls.MAX_ENTRIES:
            raise SelectionStoreError("Selection file has an invalid selections table")
        for key, selection in selections.items():
            try:
                cls._validate_key(key)
            except ValueError as exc:
                raise SelectionStoreError("Selection file contains an invalid save identity") from exc
            if not isinstance(selection, dict) or set(selection) != {"seed", "slot"}:
                raise SelectionStoreError("Selection file contains an invalid pet selection")
            seed = selection["seed"]
            if not isinstance(seed, str) or len(seed) != 32 or any(
                char not in "0123456789abcdef" for char in seed
            ):
                raise SelectionStoreError("Selection file contains an invalid pet seed")
            try:
                cls._validate_slot(selection["slot"])
            except ValueError as exc:
                raise SelectionStoreError("Selection file contains an invalid pet slot") from exc
        return document

    def _read(self):
        try:
            with self.path.open("rb") as source:
                raw = source.read(self.MAX_BYTES + 1)
        except FileNotFoundError:
            return {"schema": self.SCHEMA, "selections": {}}
        except OSError as exc:
            raise SelectionStoreError("Cannot read the selection file") from exc
        if len(raw) > self.MAX_BYTES:
            raise SelectionStoreError("Selection file exceeds the 1 MiB limit")
        try:
            document = json.loads(raw.decode("utf-8"), object_pairs_hook=self._unique_object)
        except (UnicodeDecodeError, ValueError, RecursionError) as exc:
            raise SelectionStoreError("Selection file is not valid UTF-8 JSON") from exc
        return self._validate_document(document)

    def _write(self, document):
        self._validate_document(document)
        raw = (json.dumps(document, ensure_ascii=True, indent=2, sort_keys=True) + "\n").encode("utf-8")
        if len(raw) > self.MAX_BYTES:
            raise SelectionStoreError("Selection file would exceed the 1 MiB limit")
        temporary_path = None
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(
                mode="wb", dir=self.path.parent,
                prefix=f".{self.path.name}.", suffix=".tmp", delete=False,
            ) as target:
                temporary_path = Path(target.name)
                target.write(raw)
                target.flush()
                os.fsync(target.fileno())
            os.replace(temporary_path, self.path)
        except OSError as exc:
            raise SelectionStoreError("Cannot atomically write the selection file") from exc
        finally:
            if temporary_path is not None:
                try:
                    temporary_path.unlink(missing_ok=True)
                except OSError:
                    # A failed cleanup must not hide the original write error.
                    pass

    def load(self, save_key: str) -> dict | None:
        """Return ``{seed: lowercase hex, slot: int}``, or None if absent."""
        self._validate_key(save_key)
        selection = self._read()["selections"].get(save_key)
        return dict(selection) if selection is not None else None

    def remember(self, save_key: str, seed: bytes, slot: int):
        """Remember a 16-byte identity (JSON key seed), preserving other saves."""
        self._validate_key(save_key)
        if not isinstance(seed, bytes) or len(seed) != 16:
            raise ValueError("seed must be exactly 16 bytes")
        self._validate_slot(slot)
        document = self._read()
        document["selections"][save_key] = {"seed": seed.hex(), "slot": slot}
        self._write(document)

    def forget(self, save_key: str):
        """Remove one identity; missing entries do not create a file."""
        self._validate_key(save_key)
        document = self._read()
        if save_key in document["selections"]:
            del document["selections"][save_key]
            self._write(document)


"""Small, atomic storage for the user's AutoPet preferences.

Only the caller-supplied settings path is used. Import and construction perform
no filesystem operations; this module never reads or modifies game saves.
"""

import json
import os
from pathlib import Path
import tempfile


class SettingsStoreError(Exception):
    """Settings could not be read, validated, or replaced safely."""


class AutoPetSettingsStore:
    """Store schema-3 preferences and read legacy schema-1/2 settings.

    Missing settings use fresh defaults. Legacy settings migrate in memory only
    until an explicit save. Existing unreadable, malformed, or
    unsupported documents raise SettingsStoreError and are never overwritten.
    Each operation rereads the file; use one settings writer at a time.
    """

    SCHEMA = 3
    MAX_BYTES = 4096
    ALLOWED_LOCATIONS = frozenset({2, 3, 14})
    SELECTION_MODES = frozenset({"last_manual", "random"})

    def __init__(self, path: Path):
        self.path = Path(path)

    @classmethod
    def defaults(cls) -> dict:
        """Return independent preference defaults without filesystem access."""
        return {
            "enabled": True,
            "locations": sorted(cls.ALLOWED_LOCATIONS),
            "selection_mode": "last_manual",
            "prefer_same_biome": True,
        }

    @staticmethod
    def _unique_object(pairs):
        document = {}
        for key, value in pairs:
            if key in document:
                raise SettingsStoreError("Settings contain duplicate JSON keys")
            document[key] = value
        return document

    @classmethod
    def _validate_preferences(cls, preferences):
        if type(preferences) is not dict or set(preferences) != {
            "enabled", "locations", "selection_mode", "prefer_same_biome"
        }:
            raise ValueError("Preferences have an invalid structure")
        if type(preferences["enabled"]) is not bool:
            raise ValueError("Preferences enabled value must be boolean")
        if type(preferences["prefer_same_biome"]) is not bool:
            raise ValueError("Preferences biome preference must be boolean")
        locations = preferences["locations"]
        if type(locations) is not list or any(
            type(location) is not int or location not in cls.ALLOWED_LOCATIONS
            for location in locations
        ):
            raise ValueError("Preferences locations must be a list of allowed integer IDs")
        if len(locations) != len(set(locations)):
            raise ValueError("Preferences locations must not contain duplicate IDs")
        mode = preferences["selection_mode"]
        if type(mode) is not str or mode not in cls.SELECTION_MODES:
            raise ValueError("Preferences selection mode is unsupported")
        return {
            "enabled": preferences["enabled"],
            "locations": sorted(locations),
            "selection_mode": mode,
            "prefer_same_biome": preferences["prefer_same_biome"],
        }

    @classmethod
    def _validate_document(cls, document):
        if type(document) is not dict or "schema" not in document:
            raise SettingsStoreError("Settings have an invalid document structure")
        if type(document["schema"]) is not int or document["schema"] not in {1, 2, cls.SCHEMA}:
            raise SettingsStoreError("Settings use an unsupported schema")
        if document["schema"] == 1:
            if set(document) != {"schema", "enabled"} or type(document["enabled"]) is not bool:
                raise SettingsStoreError("Legacy settings have an invalid document structure")
            preferences = cls.defaults()
            preferences["enabled"] = document["enabled"]
            return preferences
        if document["schema"] == 2:
            if set(document) != {"schema", "enabled", "locations", "selection_mode"}:
                raise SettingsStoreError("Legacy settings have an invalid document structure")
            document = {**document, "prefer_same_biome": True}
        try:
            return cls._validate_preferences({key: value for key, value in document.items() if key != "schema"})
        except ValueError as exc:
            raise SettingsStoreError(str(exc)) from exc

    def _read(self):
        try:
            with self.path.open("rb") as source:
                raw = source.read(self.MAX_BYTES + 1)
        except FileNotFoundError:
            return self.defaults()
        except OSError as exc:
            raise SettingsStoreError("Cannot read the settings file") from exc
        if len(raw) > self.MAX_BYTES:
            raise SettingsStoreError("Settings exceed the 4 KiB limit")
        try:
            document = json.loads(raw.decode("utf-8"), object_pairs_hook=self._unique_object)
        except (UnicodeDecodeError, ValueError, RecursionError) as exc:
            raise SettingsStoreError("Settings are not valid UTF-8 JSON") from exc
        return self._validate_document(document)

    def load_preferences(self) -> dict:
        """Read all preferences; do not create or migrate a file on disk."""
        return self._read()

    def save_preferences(self, preferences: dict) -> None:
        """Atomically save valid preferences, preserving invalid existing files."""
        # Validate before creating directories or writing a temporary file.
        validated = self._validate_preferences(preferences)
        self._read()
        self._persist(validated)

    def load(self) -> bool:
        """Compatibility helper returning only the enabled preference."""
        return self.load_preferences()["enabled"]

    def save(self, enabled: bool) -> None:
        """Change enabled only, preserving existing location and selection choices."""
        if type(enabled) is not bool:
            raise ValueError("enabled must be a boolean")
        preferences = self._read()
        preferences["enabled"] = enabled
        self._persist(preferences)

    def _persist(self, preferences):
        document = {"schema": self.SCHEMA, **preferences}
        raw = (json.dumps(document, sort_keys=True, indent=2) + "\n").encode("utf-8")
        temporary_path = None
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(
                mode="wb", dir=self.path.parent,
                prefix=f".{self.path.name}.", suffix=".tmp", delete=False,
            ) as target:
                temporary_path = Path(target.name)
                target.write(raw)
                target.flush()
                os.fsync(target.fileno())
            os.replace(temporary_path, self.path)
        except OSError as exc:
            raise SettingsStoreError("Cannot atomically write the settings file") from exc
        finally:
            if temporary_path is not None:
                try:
                    temporary_path.unlink(missing_ok=True)
                except OSError:
                    # Do not replace the original error with a cleanup failure.
                    pass


# This fragment is appended to policy.py by build.py. Do not install fragments.
import ctypes as C
import hashlib
import logging
import math
import os
import random
from enum import Enum
from threading import Lock
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
import time

from pymhf import Mod
from pymhf.core import _internal
from pymhf.core.hooking import static_function_hook
from pymhf.gui.decorators import BOOLEAN, ENUM, STRING


EXPECTED_EXE_SHA256 = "b7913f268dfc62386b6b68f524bfc8ade4a44a9f4fbad39085b7bf51be3680cb"
EXPECTED_PYMHF = "0.2.4"
LOGGER = logging.getLogger("AutoPet")

# All addresses are RVAs in the exact Steam 25442159 / Cosmos 7.04 executable.
# Derived offline from its native quick-menu SummonPet branch and player update.
APPLICATION_PTR_RVA = 0x6E7AAE8
LOCAL_PLAYER_OFFSET = 0x71C690
LOCATION_OFFSET = 0x57A584
ACTIVE_PET_OFFSET = 0x29A1C0
PENDING_PET_OFFSET = 0x6010
PET_TABLE_OFFSET = 0xE10D0
PET_ENTRY_SIZE = 0x24A0
PET_SEED_OFFSET = 0x2330
PET_BIRTH_TIME_OFFSET = 0x23C0
PET_RESOURCE_OFFSET = 0x2370
PET_BIOME_OFFSET = 0x2480
# Read-only offsets verified against this exact build's native pet adoption path.
SOLAR_SYSTEM_PTR_OFFSET = 0x71AF70
PLANET_COUNT_OFFSET = 0x2544
CURRENT_PLANET_INDEX_OFFSET = 0x5196D0
PLANET_ENTRY_SIZE = 0xD9170
PLANET_BIOME_OFFSET = 0x6148
PLANET_BIOME_SUBTYPE_OFFSET = 0x614C
CONCRETE_BIOMES = frozenset(range(16)) - {11}  # Exclude Test; All is 16.
SAVE_UNIVERSAL_ID_OFFSET = 0x8980
NOTIFICATIONS_OFFSET = 0x837B40
NOTICE_COUNT_OFFSET = 0x28C
NOTICE_BLOCK_OFFSET = 0x4BF50C
# Mirror the location set admitted by this build's native ownership eligibility.
# Membership alone never replaces that native check or placement validation.
SUPPORTED_SUMMON_LOCATIONS = frozenset({2, 3, 14})
DIAGNOSTIC_WAIT_LIMIT = 8
PET_ARC_OFFSET = 0x1B9140
PET_PREVIEW_OFFSET = 0x1B9300
PET_EMOTE_OFFSET = 0x1B937D
SUMMON_ARC_RANGE_RVA = 0x52381E0
SUMMON_HAND_OFFSET = 0x30E7FC
PHYSICS_CONTEXT_OFFSET = 0x2A8
PLACEMENT_PROBE_INTERVAL = 0.5
PLACEMENT_MAX_FRAME_GAP = 0.25
SelectionMode = Enum("SelectionMode", {"Last manually selected": "last_manual", "Random": "random"})


def selection_store_path():
    """Use the current Windows user's data directory, never the game folder."""
    local_data = os.environ.get("LOCALAPPDATA")
    if not local_data or not Path(local_data).is_absolute():
        raise SelectionStoreError("LOCALAPPDATA must be an absolute directory path")
    return Path(local_data) / "NMS-AutoPet" / "state.json"


def settings_store_path():
    return selection_store_path().with_name("settings.json")


def supported_runtime():
    """Gate our hooks before the mod loader instantiates this class."""
    try:
        if not _internal.IS_INJECTED or _internal.BASE_ADDRESS <= 0:
            return False
        if version("pymhf") != EXPECTED_PYMHF:
            return False
        with Path(_internal.BINARY_PATH).open("rb") as binary:
            return hashlib.file_digest(binary, "sha256").hexdigest() == EXPECTED_EXE_SHA256
    except (OSError, ValueError, TypeError, AttributeError, PackageNotFoundError):
        return False


# Each definition is a native wrapper, not a Python implementation of the game.
# No wrapper below is called during module import.
@static_function_hook(offset=0x146AC90)
def ap_queue_pet(player: C.c_void_p, slot: C.c_int32) -> None:
    ...


@static_function_hook(offset=0x146A410)
def ap_can_summon(player: C.c_void_p, slot: C.c_int32) -> C.c_bool:
    ...


@static_function_hook(offset=0x5066A0)
def ap_pet_owner_update(owner: C.c_void_p, dt: C.c_float) -> None:
    ...


@static_function_hook(offset=0x1438040)
def ap_refresh_pet_placement(arc: C.c_void_p, range1: C.c_float, range2: C.c_float,
                             hand: C.c_uint32) -> None:
    ...


@static_function_hook(offset=0x505B70)
def ap_owned_pet_eligible(owner: C.c_void_p, slot: C.c_int32) -> C.c_bool:
    ...


@static_function_hook(offset=0x60B770)
def ap_use_summon_hand() -> C.c_bool:
    ...


@static_function_hook(offset=0x17479D0)
def ap_eject(ship: C.c_void_p, player: C.c_void_p, animate: C.c_bool,
             force_during_communicator: C.c_bool) -> None:
    ...


@static_function_hook(offset=0x1479490)
def ap_enter_cockpit(player: C.c_void_p) -> None:
    ...


@static_function_hook(offset=0x1440CD0)
def ap_player_update(player: C.c_void_p, dt: C.c_float) -> None:
    ...


@static_function_hook(offset=0x56FA50)
def ap_load_save(player_state: C.c_void_p, common_data: C.c_void_p, state_data: C.c_void_p,
                 network_client: C.c_bool, resetting: C.c_bool, arg6: C.c_uint32) -> C.c_bool:
    ...


@static_function_hook(offset=0x9B8300)
def ap_add_timed_message(notifications: C.c_void_p, message: C.c_void_p,
                         duration: C.c_float, colour: C.c_void_p,
                         audio: C.c_uint32, icon: C.c_void_p,
                         flag7: C.c_bool, extra_time: C.c_float,
                         flag9: C.c_bool, flag10: C.c_bool, flag11: C.c_bool) -> None:
    ...


class AutoPet(Mod):
    """Experimental summon after a ship exit where native game rules permit it."""

    _disabled = not supported_runtime()

    def __init__(self):
        self.policy = AutoPetPolicy()
        self.enabled = True
        # User preference is separate from the runtime safety latch above.
        self.auto_enabled = True
        self.allowed_locations = SUPPORTED_SUMMON_LOCATIONS
        self.selection_mode_value = "last_manual"
        self.prefer_same_biome_value = True
        self.settings_store = None
        self.settings_ok = True
        self.control_lock = Lock()
        self.requested_preferences = {}
        self.pending_notice = None
        self.notifications_ok = True
        self.in_auto_call = False
        self.app_identity = None
        self.pet_identity = None
        self.store = None
        self.save_key = None
        self.saved_selection = None
        self.persistence_ok = True
        self._exit_diagnostic = None
        self._placement_warmed = False
        self._pending_pet_identity = None
        self._next_probe_at = 0.0
        self._probe_primed_at = None
        self._probe_location = None
        self._probe_physics_context = None
        self._queue_rejection_logged = False
        # Mod.__init__ uses inspect.getmembers(self), which evaluates properties.
        # Initialize their backing fields before the framework discovers them.
        super().__init__()
        try:
            self.store = PetSelectionStore(selection_store_path())
        except SelectionStoreError:
            self._persistence_failed()
        try:
            self.settings_store = AutoPetSettingsStore(settings_store_path())
            preferences = self.settings_store.load_preferences()
            self.auto_enabled = preferences["enabled"]
            self.allowed_locations = frozenset(preferences["locations"])
            self.selection_mode_value = preferences["selection_mode"]
            self.prefer_same_biome_value = preferences["prefer_same_biome"]
        except (SelectionStoreError, SettingsStoreError):
            # An unreadable preference must not silently turn automation back on.
            self.auto_enabled = False
            self.settings_ok = False
            LOGGER.exception("AutoPet settings unavailable; automation starts OFF. The settings panel can enable it for this session.")
        LOGGER.info("AutoPet 0.4.1 experimental: automation %s; use the AutoPet settings panel.",
                    "ON" if self.auto_enabled else "OFF")

    @property
    @BOOLEAN("Automatically summon companion after ship exit")
    def automatic_summoning(self):
        if not self.enabled:
            return False
        return self._visible_preferences()["enabled"]

    @automatic_summoning.setter
    def automatic_summoning(self, value):
        # The GUI runs on another thread. Queue the latest desired state only;
        # file persistence and all game operations happen on local Player.Update.
        if type(value) is bool:
            self._queue_preference("enabled", value)

    @property
    @BOOLEAN("Planets")
    def planets(self):
        return 3 in self._visible_preferences()["locations"]

    @planets.setter
    def planets(self, value):
        if type(value) is bool:
            self._queue_preference("planets", value)

    @property
    @BOOLEAN("Space stations")
    def space_stations(self):
        return 2 in self._visible_preferences()["locations"]

    @space_stations.setter
    def space_stations(self, value):
        if type(value) is bool:
            self._queue_preference("space_stations", value)

    @property
    @BOOLEAN("Nexus")
    def nexus(self):
        return 14 in self._visible_preferences()["locations"]

    @nexus.setter
    def nexus(self, value):
        if type(value) is bool:
            self._queue_preference("nexus", value)

    @property
    @ENUM("Companion selection", SelectionMode)
    def companion_selection(self):
        return SelectionMode(self._visible_preferences()["selection_mode"])

    @companion_selection.setter
    def companion_selection(self, value):
        if isinstance(value, SelectionMode):
            self._queue_preference("selection_mode", value.value)

    @property
    @BOOLEAN("Prefer same biome in Random mode")
    def prefer_same_biome(self):
        return self._visible_preferences()["prefer_same_biome"]

    @prefer_same_biome.setter
    def prefer_same_biome(self, value):
        if type(value) is bool:
            self._queue_preference("prefer_same_biome", value)

    def _queue_preference(self, key, value):
        if self.enabled:
            with self.control_lock:
                self.requested_preferences[key] = value

    def _current_preferences(self):
        return {"enabled": self.auto_enabled, "locations": sorted(self.allowed_locations),
                "selection_mode": self.selection_mode_value,
                "prefer_same_biome": self.prefer_same_biome_value}

    def _merged_preferences_locked(self):
        preferences = self._current_preferences()
        for key in ("enabled", "selection_mode", "prefer_same_biome"):
            if key in self.requested_preferences:
                preferences[key] = self.requested_preferences[key]
        locations = set(preferences["locations"])
        for key, location in (("planets", 3), ("space_stations", 2), ("nexus", 14)):
            if key in self.requested_preferences:
                if self.requested_preferences[key]:
                    locations.add(location)
                else:
                    locations.discard(location)
        preferences["locations"] = sorted(locations)
        return preferences

    def _visible_preferences(self):
        with self.control_lock:
            return self._merged_preferences_locked()

    def _controls_pending(self):
        with self.control_lock:
            return bool(self.requested_preferences)

    @property
    @STRING("Status")
    def control_status(self):
        if not self.enabled:
            return "Stopped after a runtime error; restart required."
        if self._controls_pending():
            return "Change pending; return to the game to apply and save."
        suffix = "" if self.settings_ok else " (session only)"
        if self.auto_enabled and self.policy.pending:
            return "Waiting for a suitable place" + suffix
        return ("Automatic summoning ON" if self.auto_enabled else "Automatic summoning OFF") + suffix

    @property
    @STRING("Companion")
    def companion_status(self):
        if self._visible_preferences()["selection_mode"] == "random":
            return "Random eligible owned companion per exit; manual favorite is preserved."
        slot = self.policy.last_slot
        if slot is not None:
            return f"Selected companion: slot {slot + 1}"
        if self.saved_selection is not None:
            return "Remembered companion; ownership checked on next ship exit."
        return "No companion selected. Summon one manually in the game."

    def _apply_control(self):
        with self.control_lock:
            if not self.requested_preferences:
                return
            previous = self._current_preferences()
            requested = self._merged_preferences_locked()
            self.requested_preferences = {}
            if requested == previous:
                return
            self.auto_enabled = requested["enabled"]
            self.allowed_locations = frozenset(requested["locations"])
            self.selection_mode_value = requested["selection_mode"]
            self.prefer_same_biome_value = requested["prefer_same_biome"]
        self._finish_exit_diagnostic("cancelled by settings change")
        self.policy.enter_ship()  # Cancel pending summons; retain the chosen pet.
        if self.settings_ok:
            try:
                self.settings_store.save_preferences(requested)
            except SettingsStoreError:
                self.settings_ok = False
                LOGGER.exception("AutoPet toggle applies to this session only; settings file preserved.")
        state = "ON" if self.auto_enabled else "OFF"
        suffix = "" if self.settings_ok else " (session only)"
        self.pending_notice = (f"AutoPet: {state}{suffix}" if previous["enabled"] != self.auto_enabled
                               else f"AutoPet: settings updated{suffix}")
        LOGGER.info(self.pending_notice)
        LOGGER.info("AutoPet preferences: locations=%s selection=%s prefer_same_biome=%s.",
                    requested["locations"], requested["selection_mode"], requested["prefer_same_biome"])

    def _finish_exit_diagnostic(self, reason):
        # All cancellation/context transitions invalidate the previous ray jobs
        # for automation. The game owns their actual cleanup; never alter them.
        self._reset_probe()
        self._pending_pet_identity = None
        self._queue_rejection_logged = False
        if self._exit_diagnostic is not None:
            LOGGER.info("AutoPet exit finished: %s.", reason)
            self._exit_diagnostic = None

    def _trace_policy_tick(self, now, *, location, advancing, active_pet, native_pending,
                           eligible, slot, wait_reason=None):
        """Describe existing observations; never change policy or query the game.

        Unchanged frames are silent. Cap wait transitions per exit, while always
        retaining the terminal result and the small set of observed wait reasons.
        """
        diagnostic = self._exit_diagnostic
        if diagnostic is None:
            return
        if active_pet >= 0:
            reason = "active_companion"
        elif native_pending >= 0:
            reason = "native_pending_companion"
        elif location not in SUPPORTED_SUMMON_LOCATIONS:
            reason = "not_summon_location"
        elif location not in self.allowed_locations:
            reason = "location_disabled"
        elif not advancing:
            reason = "paused_or_zero_dt"
        elif wait_reason is not None:
            reason = wait_reason
        elif not eligible:
            reason = "eligibility_false"
        else:
            reason = "stability_delay"
        elapsed = now - diagnostic["armed_at"]
        state = (reason, location, advancing, active_pet, native_pending, eligible)
        # These are observed states, not a claim about time spent in each state
        # between callbacks. Placement failure retains the exit intent.
        if active_pet == -1 and native_pending == -1:
            diagnostic["observed_waits"].add(reason)
        if slot is not None:
            if not diagnostic.get("request_logged", False):
                LOGGER.info("AutoPet exit ready after %.2fs; requesting slot %d.", elapsed, slot + 1)
                diagnostic["request_logged"] = True
            return
        if not self.policy.pending:
            # Match the existing policy's priority: backwards clock, deadline,
            # then another active/native-pending pet. Only diagnose its result.
            if now < diagnostic["last_time"]:
                outcome = "cancelled by backwards clock"
            elif self.policy._expiry is not None and elapsed >= self.policy._expiry:
                outcome = "expired"
            elif active_pet >= 0 or native_pending >= 0:
                outcome = "cancelled by active or native-pending companion"
            else:
                outcome = "cancelled by policy"
            LOGGER.info(
                "AutoPet exit %s after %.2fs; final_wait=%s location=%d advancing=%s "
                "eligible=%s active_pet=%d native_pending_pet=%d observed_waits=%s.",
                outcome, elapsed, reason, location, advancing, eligible, active_pet, native_pending,
                ",".join(sorted(diagnostic["observed_waits"])) or "none",
            )
            self._exit_diagnostic = None
            self._placement_warmed = False
            return
        if state != diagnostic["last_state"]:
            if diagnostic["wait_logs"] < DIAGNOSTIC_WAIT_LIMIT:
                LOGGER.info(
                    "AutoPet exit waiting: %s; elapsed=%.2fs location=%d advancing=%s "
                    "eligible=%s active_pet=%d native_pending_pet=%d.",
                    reason, elapsed, location, advancing, eligible, active_pet, native_pending,
                )
                diagnostic["wait_logs"] += 1
            elif not diagnostic["suppressed"]:
                LOGGER.info("AutoPet exit wait log limit reached; further transitions suppressed until final result.")
                diagnostic["suppressed"] = True
        diagnostic["last_state"] = state
        diagnostic["last_time"] = now

    def _show_pending_notice(self, app):
        if not self.notifications_ok:
            self.pending_notice = None
            return
        if self.pending_notice is None:
            return
        try:
            notifications = app + NOTIFICATIONS_OFFSET
            # These are the native function's two early-out checks. Leave busy
            # game notifications alone and retain only our latest status message.
            if C.c_uint32.from_address(notifications + NOTICE_COUNT_OFFSET).value > 3:
                return
            if not C.c_float.from_address(app + NOTICE_BLOCK_OFFSET).value < 0:
                return
            message = C.create_string_buffer(self.pending_notice.encode("ascii")[:511], 512)
            # AddTimedMessage uses MOVAPS on the supplied RGBA, requiring 16-byte
            # alignment. Keep the allocation alive through the synchronous copy.
            colour_storage = C.create_string_buffer(31)
            colour_address = (C.addressof(colour_storage) + 15) & ~15
            colour = (C.c_float * 4).from_address(colour_address)
            colour[:] = (1.0, 1.0, 1.0, 1.0)
            empty_icon = C.c_int32(0)
            self.pending_notice = None  # One attempt, no duplicate native retry.
            ap_add_timed_message(notifications, C.addressof(message), 3.0,
                                 colour_address, 0, C.addressof(empty_icon),
                                 False, 0.0, False, False, False)
        except Exception:
            self.notifications_ok = False
            self.pending_notice = None
            LOGGER.exception("AutoPet HUD confirmation unavailable; see the settings panel for status.")

    def _app_for_player(self, player):
        app = C.c_void_p.from_address(_internal.BASE_ADDRESS + APPLICATION_PTR_RVA).value
        if not app:
            self._finish_exit_diagnostic("cancelled because application context is unavailable")
            self.policy.reset()
            self.app_identity = None
            self.pet_identity = None
            self.save_key = None
            self.saved_selection = None
            self.pending_notice = None
            return None
        if app != self.app_identity:
            self._finish_exit_diagnostic("cancelled because application context changed")
            if self.app_identity is not None:
                # A replacement application without an observed successful load
                # must not inherit the last save's persisted selection.
                self.save_key = None
                self.saved_selection = None
                self.pending_notice = None
            self.policy.reset()
            self.pet_identity = None
            self.app_identity = app
        return app if player == app + LOCAL_PLAYER_OFFSET else None

    @staticmethod
    def _pet_seed(app, slot):
        # Persistent 128-bit identity: CreatureSeed uint64 + BirthTime uint64.
        # Both are copied to/from GcPetData by this build's pet load/save paths.
        # Exclude GcSeed padding and the lazily generated BoneScaleSeed at 0x2390.
        entry = app + PET_TABLE_OFFSET + slot * PET_ENTRY_SIZE
        return (C.string_at(entry + PET_SEED_OFFSET, 8)
                + C.string_at(entry + PET_BIRTH_TIME_OFFSET, 8))

    def _restore_selected(self, app):
        if self.policy.last_slot is not None:
            if self._pet_seed(app, self.policy.last_slot) == self.pet_identity:
                return
            self._finish_exit_diagnostic("cancelled because companion identity changed")
            self.policy.reset()
            self.pet_identity = None
        if self.save_key is None or self.saved_selection is None:
            return
        identity = bytes.fromhex(self.saved_selection["seed"])
        matches = []
        for slot in range(30):
            entry = app + PET_TABLE_OFFSET + slot * PET_ENTRY_SIZE
            if C.c_uint32.from_address(entry + PET_RESOURCE_OFFSET).value == 0:
                continue
            if self._pet_seed(app, slot) == identity:
                matches.append(slot)
        # Do not guess between duplicates or summon a replacement at an old slot.
        if len(matches) == 1:
            self.policy.remember(matches[0])
            self.pet_identity = identity
            LOGGER.info("AutoPet restored the remembered pet for this save (slot %d).", matches[0] + 1)

    def _persistence_failed(self):
        self.persistence_ok = False
        LOGGER.exception("AutoPet persistence unavailable; manual selection still works for this session. File preserved.")

    def _fail_closed(self):
        self.enabled = False
        self._finish_exit_diagnostic("cancelled by runtime error")
        self.policy.reset()
        self.pending_notice = None
        LOGGER.exception("AutoPet disabled after a runtime error. Restart before trying again.")

    @ap_queue_pet.after
    def remember_pet(self, player, slot):
        if not self.enabled or self.in_auto_call:
            return
        try:
            app = self._app_for_player(player)
            if app is None:
                return
            # The game sets pending=-1 if preparing the pet failed.
            if 0 <= slot < 30 and C.c_int32.from_address(player + PENDING_PET_OFFSET).value == slot:
                previous_identity = self.saved_selection["seed"] if self.saved_selection else None
                self._finish_exit_diagnostic("cancelled by successful manual companion selection")
                self.policy.remember(slot)
                self.pet_identity = self._pet_seed(app, slot)
                self.saved_selection = {"seed": self.pet_identity.hex(), "slot": slot}
                if self.save_key is not None and self.persistence_ok:
                    try:
                        self.store.remember(self.save_key, self.pet_identity, slot)
                    except SelectionStoreError:
                        self._persistence_failed()
                if self.pet_identity.hex() != previous_identity:
                    if self.auto_enabled and self.selection_mode_value == "random":
                        self.pending_notice = "AutoPet: manual favorite saved. Random selection remains ON."
                    elif self.auto_enabled:
                        self.pending_notice = "AutoPet: companion selected for automatic summon after ship exit."
                    else:
                        self.pending_notice = "AutoPet: companion selected. Automatic summoning is OFF."
                LOGGER.info("AutoPet selected companion slot %d.", slot + 1)
        except Exception:
            self._fail_closed()

    @ap_eject.after
    def after_exit_request(self, ship, player, animate, force_during_communicator):
        if not self.enabled or not self.auto_enabled:
            return
        try:
            app = self._app_for_player(player)
            if app is not None:
                self._restore_selected(app)
                self._finish_exit_diagnostic("replaced by another ship exit")
                now = time.monotonic()
                random_selection = self.selection_mode_value == "random"
                self.policy.eject(now, random_selection=random_selection)
                if self.policy.pending:
                    self._pending_pet_identity = None if random_selection else self.pet_identity
                    self._exit_diagnostic = {
                        "armed_at": now, "last_time": now, "last_state": None,
                        "wait_logs": 0, "suppressed": False, "observed_waits": set(),
                    }
                    choice = ("one random eligible companion" if random_selection
                              else f"slot {self.policy.pending_slot + 1}")
                    LOGGER.info("AutoPet ship exit armed for %s; stability delay=%.2fs; waiting until a suitable place.",
                                choice, self.policy._delay)
                elif self.policy.last_slot is None:
                    LOGGER.info("AutoPet ship exit not armed: no selected owned companion.")
                else:
                    LOGGER.info("AutoPet ship exit not armed: policy rejected the exit timestamp.")
        except Exception:
            self._fail_closed()

    @ap_enter_cockpit.before
    def before_enter_ship(self, player):
        if not self.enabled:
            return
        try:
            if self._app_for_player(player) is not None:
                self._finish_exit_diagnostic("cancelled by entering the ship")
                self.policy.enter_ship()
        except Exception:
            self._fail_closed()

    @ap_load_save.before
    def before_load(self, player_state, common_data, state_data, network_client, resetting, arg6):
        # Network-client deserialization must not erase the local user's selection.
        if not network_client:
            self._finish_exit_diagnostic("cancelled by main save load")
            self.policy.reset()
            self.app_identity = None
            self.pet_identity = None
            self.save_key = None
            self.saved_selection = None
            self.pending_notice = None

    @ap_load_save.after
    def after_load(self, player_state, common_data, state_data, network_client, resetting, arg6, _result_):
        if not self.enabled or network_client or not _result_:
            return
        try:
            # This is GcPlayerCommonStateData, not GcPlayerStateData. The ID is
            # copied from +0x8980 in this exact executable's LoadFromData body.
            if not common_data:
                return
            save_id = C.c_uint64.from_address(common_data + SAVE_UNIVERSAL_ID_OFFSET).value
            if save_id == 0:
                LOGGER.warning("AutoPet: save has no persistent ID; selection lasts for this session only.")
                return
            self.save_key = f"nms:{save_id:016x}"
            if self.persistence_ok:
                try:
                    self.saved_selection = self.store.load(self.save_key)
                except SelectionStoreError:
                    self._persistence_failed()
            # Ownership may still be loading. Resolve the pet only on an exit,
            # and leave ordinary save loading free of new summon requests.
        except Exception:
            self._fail_closed()

    @ap_player_update.after
    def after_player_update(self, player, dt):
        if not self.enabled:
            return
        if not self._controls_pending() and self.pending_notice is None:
            return
        try:
            app = self._app_for_player(player)
            if app is None:
                return
            self._apply_control()
            if math.isfinite(dt) and dt > 0:
                self._show_pending_notice(app)
        except Exception:
            self._fail_closed()

    @ap_pet_owner_update.after
    def after_pet_owner_update(self, owner, dt):
        # Ownership.Update normally resets placement after closing the pet menu.
        # Refresh only after that reset, and check/queue within this same callback.
        if not self.enabled or not self.auto_enabled or not self.policy.pending:
            return
        # Player.Update applies UI controls. If ownership runs first, an OFF
        # request must prevent automation immediately without doing GUI-thread I/O.
        if self._controls_pending():
            self._reset_probe()
            return
        try:
            player = owner - PET_TABLE_OFFSET + LOCAL_PLAYER_OFFSET
            app = self._app_for_player(player)
            if app is None or not self.policy.pending:
                return
            selected = self.policy.pending_slot
            if selected is not None and self._pending_pet_identity != self._pet_seed(app, selected):
                self._finish_exit_diagnostic("cancelled because companion identity changed")
                if self.selection_mode_value == "last_manual":
                    self.policy.reset()
                    self.pet_identity = None
                    LOGGER.info("AutoPet forgot a companion slot whose identity changed.")
                else:
                    self.policy.enter_ship()
                return
            preview_slot = C.c_int32.from_address(owner + PET_PREVIEW_OFFSET).value
            emote_active = C.c_ubyte.from_address(owner + PET_EMOTE_OFFSET).value
            if preview_slot != -1 or emote_active != 0:
                self._finish_exit_diagnostic("cancelled because the native pet preview or emote is active")
                self.policy.enter_ship()
                return
            location = C.c_int32.from_address(app + LOCATION_OFFSET).value
            if location in SUPPORTED_SUMMON_LOCATIONS and location not in self.allowed_locations:
                self._finish_exit_diagnostic("cancelled because this location is disabled in settings")
                self.policy.enter_ship()
                return
            active_pet = C.c_int32.from_address(app + ACTIVE_PET_OFFSET).value
            native_pending = C.c_int32.from_address(player + PENDING_PET_OFFSET).value
            advancing = math.isfinite(dt) and dt > 0
            on_foot = (location in SUPPORTED_SUMMON_LOCATIONS
                       and location in self.allowed_locations and advancing)
            # Reject unexpected index values instead of treating corrupt state as "no pet".
            if not (-1 <= active_pet < 30 and -1 <= native_pending < 30):
                self._finish_exit_diagnostic(
                    f"cancelled by invalid companion indices (active={active_pet}, pending={native_pending})")
                self.policy.enter_ship()
                return
            now = time.monotonic()
            within_window = (now >= self.policy._last_time
                             and (self.policy._expiry is None
                                  or now - self.policy._ejected_at < self.policy._expiry))
            can_try = on_foot and active_pet == -1 and native_pending == -1 and within_window
            eligible = False
            wait_reason = None
            if can_try:
                eligible, wait_reason = self._probe_placement(app, owner, player, location, now)
            else:
                self._reset_probe()
                if not within_window:
                    # No new native check at/after expiry. Report the last
                    # observed wait, rather than inventing a fresh false result.
                    previous = self._exit_diagnostic and self._exit_diagnostic["last_state"]
                    wait_reason = previous[0] if previous else "deadline_before_placement_check"
            chosen_identity = self._pending_pet_identity
            slot = self.policy.tick(now, on_foot_in_summon_location=on_foot,
                                    active_pet=active_pet, native_pending_pet=native_pending,
                                    eligible=eligible)
            self._trace_policy_tick(now, location=location, advancing=advancing,
                                    active_pet=active_pet, native_pending=native_pending,
                                    eligible=eligible, slot=slot, wait_reason=wait_reason)
            if not self.policy.pending:
                self._pending_pet_identity = None
                self._reset_probe()
            if slot is None:
                return
            if self.selection_mode_value == "random":
                # Pool scans may inspect other slots after the eventual choice.
                # Revalidate the frozen choice immediately before each paced
                # queue attempt. A temporary failure retains it, never rerolls.
                if (self._pet_seed(app, slot) != chosen_identity
                        or not self._slot_occupied(app, slot)
                        or not self._native_owned(owner, slot)
                        or not self._native_can_summon(player, slot)):
                    self.policy.resolve(False)
                    self._reset_probe(next_at=now + PLACEMENT_PROBE_INTERVAL)
                    return
            # Only an accepted native queue consumes the intent. Rejection waits
            # for a fresh throttled placement pair before retrying the same pet.
            self.in_auto_call = True
            try:
                ap_queue_pet(player, slot)
            finally:
                self.in_auto_call = False
            queued_slot = C.c_int32.from_address(player + PENDING_PET_OFFSET).value
            if queued_slot == -1:
                self.policy.resolve(False)
                self._reset_probe(next_at=now + PLACEMENT_PROBE_INTERVAL)
                if not self._queue_rejection_logged:
                    LOGGER.info("AutoPet queue was not accepted; waiting for a suitable place with the same companion.")
                    self._queue_rejection_logged = True
                return
            if queued_slot != slot:
                self.enabled = False
                self.policy.reset()
                LOGGER.error("AutoPet disabled: unexpected queued companion after summon request.")
                return
            self.policy.resolve(True)
            self._finish_exit_diagnostic("summon request accepted")
            LOGGER.info("AutoPet queued slot %d through the game's normal summon path.", slot + 1)
        except Exception:
            self._fail_closed()

    @staticmethod
    def _slot_occupied(app, slot):
        return C.c_uint32.from_address(app + PET_TABLE_OFFSET + slot * PET_ENTRY_SIZE
                                       + PET_RESOURCE_OFFSET).value != 0

    @staticmethod
    def _native_owned(owner, slot):
        result = ap_owned_pet_eligible(owner, slot)
        if result is None:
            raise RuntimeError("Native companion ownership eligibility call failed.")
        return bool(result)

    @staticmethod
    def _native_can_summon(player, slot):
        result = ap_can_summon(player, slot)
        if result is None:
            raise RuntimeError("Native summon eligibility call failed.")
        return bool(result)

    @staticmethod
    def _pet_biome(app, slot):
        # GcPetData.Biome is copied unchanged into each runtime pet entry.
        biome = C.c_uint32.from_address(app + PET_TABLE_OFFSET + slot * PET_ENTRY_SIZE
                                        + PET_BIOME_OFFSET).value
        return biome if biome in CONCRETE_BIOMES else None

    @staticmethod
    def _current_planet_biome(app):
        """Read and normalize the current planet as native pet adoption does."""
        if not app:
            return None
        solar = C.c_void_p.from_address(app + SOLAR_SYSTEM_PTR_OFFSET).value
        if not solar:
            return None
        count = C.c_int32.from_address(solar + PLANET_COUNT_OFFSET).value
        if not 1 <= count <= 6:
            return None
        index = C.c_int32.from_address(solar + CURRENT_PLANET_INDEX_OFFSET).value
        if not 0 <= index < count:
            return None
        planet = solar + index * PLANET_ENTRY_SIZE
        biome = C.c_uint32.from_address(planet + PLANET_BIOME_OFFSET).value
        subtype = C.c_uint32.from_address(planet + PLANET_BIOME_SUBTYPE_OFFSET).value
        if biome not in CONCRETE_BIOMES or not 0 <= subtype <= 31:
            return None
        # Adoption maps these subtypes before its special-biome normalization.
        if subtype == 25:
            return 12  # Swamp
        if subtype == 26:
            return 13  # Lava
        return 7 if biome in {8, 9, 10} else biome  # Weird variants

    def _random_biome_pool(self, app, location, candidates):
        """Prefer matching habitat only within the already eligible random pool.

        Unknown planet data or no known match leaves every eligible candidate
        available. The readers can be replaced by owned-memory adapters in tests.
        """
        if (not self.prefer_same_biome_value or self.selection_mode_value != "random"
                or location != 3):
            return candidates
        try:
            biome = self._current_planet_biome(app)
            if biome is None:
                return candidates
            matching = [slot for slot in candidates if self._pet_biome(app, slot) == biome]
        except (OSError, ValueError):
            # Habitat is optional. A recoverable read failure must not replace
            # the native ownership/placement decision or stop ordinary random.
            return candidates
        return matching or candidates

    def _refresh_placement(self, app, owner):
        arc_range = C.c_float.from_address(_internal.BASE_ADDRESS + SUMMON_ARC_RANGE_RVA).value
        if not math.isfinite(arc_range) or arc_range <= 0:
            raise RuntimeError("Native summon placement range is invalid.")
        use_hand = ap_use_summon_hand()
        if use_hand is None:
            raise RuntimeError("Native summon hand selection call failed.")
        hand = C.c_uint32.from_address(app + SUMMON_HAND_OFFSET).value if use_hand else 0
        warmed = self._placement_warmed
        ap_refresh_pet_placement(owner + PET_ARC_OFFSET, arc_range, arc_range, hand)
        self._placement_warmed = True
        return warmed

    def _reset_probe(self, *, next_at=0.0):
        self._placement_warmed = False
        self._probe_primed_at = None
        self._probe_location = None
        self._probe_physics_context = None
        self._next_probe_at = next_at

    def _probe_placement(self, app, owner, player, location, now):
        physics_context = C.c_uint64.from_address(player + PHYSICS_CONTEXT_OFFSET).value
        if not physics_context:
            self._reset_probe(next_at=now + PLACEMENT_PROBE_INTERVAL)
            return False, "physics_context_unavailable"
        primed = (self._probe_primed_at is not None and self._probe_location == location
                  and self._probe_physics_context == physics_context
                  and 0 < now - self._probe_primed_at <= PLACEMENT_MAX_FRAME_GAP)
        if self._probe_primed_at is not None and not primed:
            self._reset_probe()
        if not primed and now < self._next_probe_at:
            return False, "probe_wait"
        selected = self.policy.pending_slot
        if selected is None:
            candidates = [slot for slot in range(30)
                          if self._slot_occupied(app, slot) and self._native_owned(owner, slot)]
        else:
            candidates = [selected] if self._native_owned(owner, selected) else []
        if not candidates:
            self._reset_probe(next_at=now + PLACEMENT_PROBE_INTERVAL)
            return False, "ownership_eligibility_false"
        self._refresh_placement(app, owner)
        if not primed:
            self._probe_primed_at = now
            self._probe_location = location
            self._probe_physics_context = physics_context
            return False, "placement_warmup"
        # The immediately following usable owner callback consumes newly primed
        # ray results. Never use a pair separated by a pause or a large frame gap.
        self._reset_probe(next_at=now + PLACEMENT_PROBE_INTERVAL)
        candidates = [slot for slot in candidates if self._native_can_summon(player, slot)]
        if not candidates:
            return False, "eligibility_false"
        if selected is None:
            candidates = self._random_biome_pool(app, location, candidates)
            slot = random.choice(candidates)
            self.policy.select_for_exit(slot)
            self._pending_pet_identity = self._pet_seed(app, slot)
            LOGGER.info("AutoPet chose random companion slot %d from %d eligible owned companions for this exit.",
                        slot + 1, len(candidates))
        return True, None


if AutoPet._disabled:
    LOGGER.error("AutoPet is disabled: requires pyMHF 0.2.4 and the exact supported NMS.exe SHA256.")
