"""Build a standalone source mod; never installs or launches anything."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HEADER = '''# /// script
# requires-python = ">=3.11,<3.14"
# dependencies = ["pymhf[gui]==0.2.4"]
#
# [tool.pymhf]
# exe = "NMS.exe"
# steam_gameid = 275850
# start_paused = false
# interactive_console = false
#
# [tool.pymhf.logging]
# shown = false
# log_dir = "{CURR_DIR}"
# log_level = "info"
#
# [tool.pymhf.gui]
# shown = true
# always_on_top = false
# ///
# Companion Auto Summon 0.4.3 EXPERIMENTAL — one deferred summon opportunity after local save load.
# Generated by build.py. Edit src/, then rebuild.

'''

def build():
    result = HEADER + (ROOT / "src/policy.py").read_text(encoding="utf-8")
    result += "\n\n" + (ROOT / "src/persistence.py").read_text(encoding="utf-8")
    result += "\n\n" + (ROOT / "src/settings.py").read_text(encoding="utf-8")
    result += "\n\n" + (ROOT / "src/runtime.py").read_text(encoding="utf-8")
    compile(result, "CompanionAutoSummon.py", "exec")  # Parse only; no import, native call or injection.
    target = ROOT / "CompanionAutoSummon.py"
    target.write_text(result, encoding="utf-8", newline="\n")
    print(target)

if __name__ == "__main__":
    build()
